"use client"

import { useState } from "react"
import { Bot, PlayCircle, Settings, CheckCircle, XCircle, Loader2 } from "lucide-react"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Textarea } from "@/components/ui/textarea"
import { Badge } from "@/components/ui/badge"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { testAIIntegration, getAIModelInfo } from "@/lib/actions/ai"
import { getAgents } from "@/lib/actions/agents"
import { useSession } from "next-auth/react"

interface Agent {
  id: string
  name: string
  emoji: string
  color: string
  style: string
  prompt: string
}

export function AITestingPanel() {
  const { data: session } = useSession()
  const [isLoading, setIsLoading] = useState(false)
  const [isTestRunning, setIsTestRunning] = useState(false)
  const [testResult, setTestResult] = useState<{
    success: boolean
    message: string
  } | null>(null)
  const [selectedAgent, setSelectedAgent] = useState<string>("")
  const [testPrompt, setTestPrompt] = useState("")
  const [testResponse, setTestResponse] = useState<{
    content: string
    model: string
    usage: any
    processingTime?: number
  } | null>(null)
  const [agents, setAgents] = useState<Agent[]>([])
  const [modelInfo, setModelInfo] = useState<any>(null)

  // Load agents and model info on mount
  const loadData = async () => {
    if (!session?.user?.id) return

    try {
      const [agentsResult, modelResult] = await Promise.all([
        getAgents(session.user.id),
        getAIModelInfo()
      ])

      if (agentsResult.success && agentsResult.data) {
        setAgents(agentsResult.data)
        if (agentsResult.data.length > 0) {
          setSelectedAgent(agentsResult.data[0].id)
        }
      }

      if (modelResult.success) {
        setModelInfo(modelResult.data)
      }
    } catch (error) {
      console.error("Error loading data:", error)
    }
  }

  useState(() => {
    loadData()
  })

  const handleTestConnection = async () => {
    setIsLoading(true)
    setTestResult(null)

    try {
      const result = await testAIIntegration()
      setTestResult(result)
    } catch (error) {
      setTestResult({
        success: false,
        message: error instanceof Error ? error.message : "Unknown error occurred"
      })
    } finally {
      setIsLoading(false)
    }
  }

  const handleTestAgentResponse = async () => {
    if (!selectedAgent || !testPrompt.trim() || !session?.user?.id) return

    setIsTestRunning(true)
    setTestResponse(null)

    try {
      // This would call the actual AI response generation
      // For now, we'll simulate it
      await new Promise(resolve => setTimeout(resolve, 2000))

      setTestResponse({
        content: `This is a simulated AI response from ${agents.find(a => a.id === selectedAgent)?.name}. In the actual implementation, this would be a real response generated by Z.ai's GLM model based on the agent's personality and style.`,
        model: modelInfo?.currentModel || "glm-4.5-flash",
        usage: {
          prompt_tokens: testPrompt.length,
          completion_tokens: 150,
          total_tokens: testPrompt.length + 150
        },
        processingTime: 1250
      })
    } catch (error) {
      console.error("Error testing agent response:", error)
    } finally {
      setIsTestRunning(false)
    }
  }

  const selectedAgentData = agents.find(a => a.id === selectedAgent)

  return (
    <div className="space-y-6">
      {/* Connection Test */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Settings className="h-5 w-5" />
            AI Integration Status
          </CardTitle>
          <CardDescription>
            Test the connection to Z.ai API and verify integration is working
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="flex items-center justify-between">
            <div className="space-y-1">
              <p className="text-sm font-medium">API Connection</p>
              <p className="text-xs text-muted-foreground">
                {testResult ? (
                  <span className={`flex items-center gap-1 ${
                    testResult.success ? "text-green-600" : "text-red-600"
                  }`}>
                    {testResult.success ? (
                      <CheckCircle className="h-3 w-3" />
                    ) : (
                      <XCircle className="h-3 w-3" />
                    )}
                    {testResult.message}
                  </span>
                ) : (
                  "Click test to verify connection"
                )}
              </p>
            </div>
            
            <Button
              onClick={handleTestConnection}
              disabled={isLoading}
              variant={testResult?.success ? "outline" : "default"}
            >
              {isLoading ? (
                <>
                  <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                  Testing...
                </>
              ) : (
                "Test Connection"
              )}
            </Button>
          </div>

          {modelInfo && (
            <div className="mt-4 p-3 bg-muted rounded-lg">
              <p className="text-xs font-medium mb-2">Current Configuration:</p>
              <div className="space-y-1 text-xs text-muted-foreground">
                <p>Model: {modelInfo.currentModel}</p>
                <p>Available Models: {modelInfo.availableModels.length}</p>
              </div>
            </div>
          )}
        </CardContent>
      </Card>

      {/* Agent Response Test */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Bot className="h-5 w-5" />
            Agent Response Testing
          </CardTitle>
          <CardDescription>
            Test how your agents respond to different prompts using real AI
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          {/* Agent Selection */}
          <div className="space-y-2">
            <label className="text-sm font-medium">Select Agent</label>
            <Select value={selectedAgent} onValueChange={setSelectedAgent}>
              <SelectTrigger>
                <SelectValue placeholder="Choose an agent to test" />
              </SelectTrigger>
              <SelectContent>
                {agents.map((agent) => (
                  <SelectItem key={agent.id} value={agent.id}>
                    <div className="flex items-center gap-2">
                      <span className="text-lg">{agent.emoji}</span>
                      <span>{agent.name}</span>
                      <Badge variant="outline" className="text-xs">
                        {agent.style.toLowerCase()}
                      </Badge>
                    </div>
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          {/* Agent Info */}
          {selectedAgentData && (
            <div className="p-3 bg-muted rounded-lg">
              <p className="text-xs font-medium mb-1">Agent Configuration:</p>
              <div className="space-y-1 text-xs text-muted-foreground">
                <p>Style: {selectedAgentData.style.toLowerCase()}</p>
                <p>Prompt: {selectedAgentData.prompt.slice(0, 100)}...</p>
              </div>
            </div>
          )}

          {/* Test Prompt */}
          <div className="space-y-2">
            <label className="text-sm font-medium">Test Prompt</label>
            <Textarea
              value={testPrompt}
              onChange={(e) => setTestPrompt(e.target.value)}
              placeholder="Enter a test prompt to see how the agent would respond..."
              rows={4}
              disabled={!selectedAgent}
            />
          </div>

          {/* Test Button */}
          <Button
            onClick={handleTestAgentResponse}
            disabled={!selectedAgent || !testPrompt.trim() || isTestRunning}
            className="w-full"
          >
            {isTestRunning ? (
              <>
                <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                Generating Response...
              </>
            ) : (
              <>
                <PlayCircle className="h-4 w-4 mr-2" />
                Test Agent Response
              </>
            )}
          </Button>

          {/* Response */}
          {testResponse && (
            <div className="space-y-4 p-4 border rounded-lg">
              <div className="flex items-center gap-2">
                <Bot className="h-4 w-4" />
                <p className="text-sm font-medium">AI Response</p>
                <Badge variant="outline" className="text-xs">
                  {testResponse.model}
                </Badge>
              </div>
              
              <div className="text-sm p-3 bg-muted rounded-lg">
                <p className="whitespace-pre-wrap">{testResponse.content}</p>
              </div>

              <div className="flex items-center justify-between text-xs text-muted-foreground">
                <div>
                  Tokens: {testResponse.usage.total_tokens} 
                  ({testResponse.usage.prompt_tokens} prompt + {testResponse.usage.completion_tokens} completion)
                </div>
                {testResponse.processingTime && (
                  <div>Processing: {testResponse.processingTime}ms</div>
                )}
              </div>
            </div>
          )}

          {/* Test Tips */}
          <div className="p-3 bg-blue-50 rounded-lg border border-blue-200">
            <p className="text-xs text-blue-800">
              <strong>💡 Tips for Testing:</strong>
            </p>
            <ul className="text-xs text-blue-700 mt-1 space-y-1">
              <li>• Test with prompts that match the agent&apos;s expertise area</li>
              <li>• Try different question styles to see how the agent adapts</li>
              <li>• Test the agent&apos;s personality by asking creative questions</li>
              <li>• Verify responses match the agent&apos;s defined style</li>
            </ul>
          </div>
        </CardContent>
      </Card>
    </div>
  )
}
